version: '3.8'

services:
  backend:
    image: trhuyle/mern-backend:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://huyle_user:Dkgh72113221@cluster0.lzelvpa.mongodb.net/cloud-lab?appName=Cluster0

  frontend:
    image: trhuyle/mern-frontend:2.0
    ports:
      - "3000:80"
    depends_on:
      - backend